apiVersion: v1
kind: Service
metadata:
  name: cdm-cloud-etcd
spec:
  clusterIP: None
  selector:
    dns: cdm-cloud-etcd

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdm-cloud-etcd
  labels:
    solution: cdm-cloud

spec:
  serviceName: cdm-cloud-etcd
  selector:
    matchLabels:
      app: cdm-cloud-etcd
  replicas: 3
  template:
    metadata:
      labels:
        app: cdm-cloud-etcd
        dns: cdm-cloud-etcd
    spec:
      restartPolicy: Always
      containers:
      - name : cdm-cloud-etcd
        image: # Enter the Docker image created from the included Dockerfile
        env:
          - name: CDM_SERVICE_ADVERTISE_PORT
            value: "2379"

          - name: CDM_SERVICE_NAME
            value: cdm-cloud-etcd

          - name: ETCD_PASSWORD
            value: "password"

          - name: ETCD_USER
            value: "cdm"

          - name: CDM_SOLUTION_NAME
            value: CDM-Cloud

          - name: CDM_SERVICE_DESCRIPTION
            value: Key-Value Store
            
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

          - name: ORCHESTRATION_TOOL
            value: kubernetes            
            