Backup:
  get:
    summary: 백업 설정 조회
    description: 설명추가
    operationId: cdm.cloud.get.backup.config
    externalDocs:
      url: http://10.1.1.220/cdm/cdm-cloud/documents/-/blob/master/functions.md#fc-cl-03091
    tags:
      - config
    responses:
      200:
        $ref: '#/components/responses/BackupConfig'
      401:
        description: Unauthenticated
      403:
        description: Unauthorized
      500:
        description: Internal Server Error
      501:
        description: Not Implemented
      503:
        description: Service Unavailable

  put:
    summary: 백업 설정 변경
    description: 설명추가
    operationId: cdm.cloud.set.backup.config
    externalDocs:
      url: http://10.1.1.220/cdm/cdm-cloud/documents/-/blob/master/functions.md#fc-cl-03101
    tags:
      - config
    requestBody:
      $ref: '#/components/requestBodies/BackupConfig'
    responses:
      200:
        $ref: '#/components/responses/BackupConfig'
      400:
        description: Bad Request
      401:
        description: Unauthenticated
      403:
        description: Unauthorized
      500:
        description: Internal Server Error
      501:
        description: Not Implemented
      503:
        description: Service Unavailable

components:
  requestBodies:
    BackupConfig:
      $ref: '#/components/responses/BackupConfig'

  responses:
    BackupConfig:
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/Config/Backup'
          examples:
            every-day-backup:
              value: {
                backup_schedule_enable: true,
                backup_schedule: {
                  type: "daily", tz: "Asia/Seoul", start-year: 2020, start-month: 1, start-day: 1,
                  interval-day: 1, hour: 0, minute: 0
                },
                backup_store_period: 12
              }
            sunday-every-2-weeks-backup:
              value: {
                backup_schedule_enable: true,
                backup_schedule: {
                  type: "weekly", tz: "Asia/Seoul", start-year: 2020, start-month: 1, start-day: 1,
                  interval-week: 2, day-of-week: "sunday", hour: 0, minute: 0
                },
                backup_store_period: 12
              }
            last-day-every-month-backup:
              value: {
                backup_schedule_enable: true,
                backup_schedule: {
                  type: "day-of-monthly", tz: "Asia/Seoul", start-year: 2020, start-month: 1, start-day: 1,
                  interval-month: 1, day-of-month: "last-day", hour: 0, minute: 0
                },
                backup_store_period: 12
              }
            last-sunday-every-month-backup:
              value: {
                backup_schedule_enable: true,
                backup_schedule: {
                  type: "week-of-monthly", tz: "Asia/Seoul", start-year: 2020, start-month: 1, start-day: 1,
                  interval-month: 1, week-of-month: "last-week", day-of-week: "sunday", hour: 0, minute: 0
                },
                backup_store_period: 12
              }
