// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: handler/test/proto/test.proto

package testp

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_test_proto_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_handler_test_proto_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_handler_test_proto_test_proto_rawDescGZIP(), []int{0}
}

type TestId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TestId) Reset() {
	*x = TestId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_test_proto_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestId) ProtoMessage() {}

func (x *TestId) ProtoReflect() protoreflect.Message {
	mi := &file_handler_test_proto_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestId.ProtoReflect.Descriptor instead.
func (*TestId) Descriptor() ([]byte, []int) {
	return file_handler_test_proto_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids  []*TestId `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Name string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag bool      `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Gid  uint64    `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_test_proto_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_handler_test_proto_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_handler_test_proto_test_proto_rawDescGZIP(), []int{2}
}

func (x *TestMessage) GetIds() []*TestId {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *TestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestMessage) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *TestMessage) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

var File_handler_test_proto_test_proto protoreflect.FileDescriptor

var file_handler_test_proto_test_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x74, 0x65, 0x73, 0x74, 0x70, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x18, 0x0a,
	0x06, 0x54, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x68, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x54, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69,
	0x64, 0x32, 0xc3, 0x02, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x07, 0x50, 0x75,
	0x74, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x1a,
	0x04, 0x2f, 0x70, 0x75, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54,
	0x65, 0x73, 0x74, 0x12, 0x0c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x12, 0x04, 0x2f, 0x67, 0x65, 0x74, 0x3a, 0x01, 0x2a,
	0x12, 0x3c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0c,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0c, 0x2a, 0x07, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x38,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x22, 0x05,
	0x2f, 0x70, 0x6f, 0x73, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x4d, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x70, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x15,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f,
	0x7b, 0x67, 0x69, 0x64, 0x7d, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x74, 0x65, 0x73,
	0x74, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_handler_test_proto_test_proto_rawDescOnce sync.Once
	file_handler_test_proto_test_proto_rawDescData = file_handler_test_proto_test_proto_rawDesc
)

func file_handler_test_proto_test_proto_rawDescGZIP() []byte {
	file_handler_test_proto_test_proto_rawDescOnce.Do(func() {
		file_handler_test_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_handler_test_proto_test_proto_rawDescData)
	})
	return file_handler_test_proto_test_proto_rawDescData
}

var file_handler_test_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_handler_test_proto_test_proto_goTypes = []interface{}{
	(*Empty)(nil),       // 0: testp.Empty
	(*TestId)(nil),      // 1: testp.TestId
	(*TestMessage)(nil), // 2: testp.TestMessage
}
var file_handler_test_proto_test_proto_depIdxs = []int32{
	1, // 0: testp.TestMessage.ids:type_name -> testp.TestId
	2, // 1: testp.Test.PutTest:input_type -> testp.TestMessage
	0, // 2: testp.Test.GetTest:input_type -> testp.Empty
	0, // 3: testp.Test.DeleteTest:input_type -> testp.Empty
	0, // 4: testp.Test.PostTest:input_type -> testp.Empty
	2, // 5: testp.Test.StreamTest:input_type -> testp.TestMessage
	0, // 6: testp.Test.PutTest:output_type -> testp.Empty
	0, // 7: testp.Test.GetTest:output_type -> testp.Empty
	0, // 8: testp.Test.DeleteTest:output_type -> testp.Empty
	0, // 9: testp.Test.PostTest:output_type -> testp.Empty
	2, // 10: testp.Test.StreamTest:output_type -> testp.TestMessage
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_handler_test_proto_test_proto_init() }
func file_handler_test_proto_test_proto_init() {
	if File_handler_test_proto_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_handler_test_proto_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_test_proto_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_test_proto_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_handler_test_proto_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_handler_test_proto_test_proto_goTypes,
		DependencyIndexes: file_handler_test_proto_test_proto_depIdxs,
		MessageInfos:      file_handler_test_proto_test_proto_msgTypes,
	}.Build()
	File_handler_test_proto_test_proto = out.File
	file_handler_test_proto_test_proto_rawDesc = nil
	file_handler_test_proto_test_proto_goTypes = nil
	file_handler_test_proto_test_proto_depIdxs = nil
}
